scp300/__init__.py
from scp300.main import bp as main_bp 
from scp300.recm import bp as recm_bp
from flask import Flask 
from config import Config
from scp300.model import database as db
from scp300.recm.predict import model
from flask_mime import Mime
# from scp300.main.mime import mime



# factory function to create python flask server dynamically 
def create_app():
    # create flask object 
    application = Flask(__name__)
    application.config.from_object(Config)
    db.init_app(application)
    # mime.init_app(application)
    application.register_blueprint(main_bp,url_prefix="/main")
    application.register_blueprint(recm_bp,url_prefix="/recm")

    return application
    

scp300/main/__init__.py
from flask import Blueprint


#blueprint initialization 
bp = Blueprint('main',__name__)
from scp300.main import routes

scp300/main/routes.py
from scp300.main import bp
from flask import render_template,current_app,request,redirect
from scp300.model.model import Face,Spectacle
from scp300.model import database as db
# from scp300.main.mime import mime 


# index page provide a portal for user to access various function 
# provide brief description for the functionality provided 
@bp.route('/index')
def index():
    return render_template('main/iGAZEhome.html')
    
@bp.route('/search',methods=['GET','POST'])
def search():
    colors = db.session.query(Spectacle.specColor).distinct().all()
    shapes = db.session.query(Spectacle.specShape).distinct().all()
    specs = Spectacle.query.all()
    if request.method == 'POST':
        color= request.form['color']
        shape= request.form['shape']
        previous = { 'color':color , 'shape':shape}
        if color == 'none' and shape == 'none' :
            specs = Spectacle.query.all()
        elif shape=='none':
            specs = Spectacle.query.filter_by(specColor=color).all()
        elif color=='none':
            specs = Spectacle.query.filter_by(specShape=shape).all()
        else:
            specs = Spectacle.query.filter_by(specShape=shape, specColor= color).all()

        return render_template('main/search.html',colors = colors, shapes = shapes, specs = specs , previous = previous )
    return render_template('main/search.html',colors = colors, shapes = shapes, specs = specs)
  

# @mime('text/html')
@bp.route('/fit')
def fit():
    # return render_template('main/threejs_new/examples/300trial.html')
    return redirect("http://localhost/threejs_new/examples/300trial.html")
    # return render_template("scp300/templates/main/threejs_new/examples/300trial.html")

scp300/model/__init__.py
from flask_sqlalchemy import SQLAlchemy

#declare sqlAlchemy to setup database 
database = SQLAlchemy()

from scp300.model import model 


scp300/recm/__init__.py
from flask import Blueprint
# Blueprint initialisation
bp = Blueprint('recm',__name__) 

from scp300.recm import routes

scp300/recm/routes.py
from scp300.recm import bp
from flask import render_template,request,flash,redirect,url_for
from flask import current_app
from werkzeug.utils import secure_filename
from scp300.model.model import Face,Spectacle
from scp300.recm.predict import model,predict_face_shape
from random import * 

import os


@bp.route('/snapshot',methods=["GET","POST"])
def snap():
    if request.method == "POST":
        f = request.files['image']
        if( f ):
            current_app.logger.info('image exist')
            current_app.logger.info(f.filename)
            #f.save(os.path.join(current_app.config['UPLOAD_FOLDER'],secure_filename(f.filename)))
            location = os.path.join(current_app.config['UPLOAD_FOLDER'],secure_filename(f.filename))
            f.save(location)
            #f.save(secure_filename(f.filename))
            flash("the face is up loaded succesfully") 
            return  url_for('recm.result')
        else:
            current_app.logger.info('image doesnt exist')     
    return render_template('recm/snapshot.html')

@bp.route('/result')
def result():
    # the return result of the query is actualy object which need to be accessed using Object.attribute else the output will be weird 
    # however sqlalchemy flask is rather confusing in the way if require more implementation might need more specifci tutorial on flask sqlalchemy 
    # sql alchemy
    shape = predict_face_shape()
    current_app.logger.info(shape)
    #shape= "heart"
    # stub variable before integrating face recognizer variable 
    face = Face.query.filter_by(faceShape=shape)
    rdnum = randint(1,500)
    return render_template('recm/result.html',shape=shape,faces=face, rand=rdnum)
    

scp300/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>iGaze System</title>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='style.css') }}">
        {% block css %}
        {% endblock %}

    </head>
    <body>
        <!-- the banner part of the webpage -->
        <!-- insert one image here -->
        <div style="display: flex;"> 
            <a href='{{ url_for("main.index") }}' style="text-decoration:none;"><input type="button" id="home" value="Home" ></a>
            <h1 id="banner"> iGaze Augmented Reality Glass Fitting System </h1>
             
        </div>
       
        <hr>
        <!-- content to be override by the child template -->
        <div id="content">
            <br>
                {% block content %}
                {% endblock %}
            <br>
        </div>
        <!-- footer -->
       
        <div id="footer" style="font-size:12px;"> 
                <p>Copyright &copy; (2019) Andrew Hii Chii Leong, Yew Vicky, Chia Jia Le
                <br>CAT300 Group Innovation Project, Academic Session 2019/2020, Semester 1</p>
        </div>


        
    </body>
</html>

scp300/templates/main/iGAZEhome.html
<!DOCTYPE html>

<html>
    <head>
        <title>iGaze HOME</title>
        <link rel="stylesheet" type="text/css" href=" {{ url_for('static',filename='main/home.css')}} ">
    </head>
    <body>
        <style>
            a{
                text-decoration:none;
            }
        </style>
        <!-- <img id="image" src="transwall.png"> -->
       
        <div id="title">
            <h1 id="igaze">iGaze</h1>
            <h3 id="about">Immersive Eyewear Fitting System</h3>
        </div>
        
        <div id="buttons">
            <div><a href='{{ url_for("recm.snap") }}'><input id="rec" type="button" value="Recommend Eyewear"></a></div>
            <div><a href='{{ url_for("main.search") }}'><input id="search" type="button" value="Search Eyewear"></a></div>
            <div><a href='{{ url_for("main.fit") }}'><input id="fit" type="button" value="Fit Eyewear"></a></div>
        </div>
        
        <div id="footer" style="font-size:12px;">
                <p>Copyright &copy; (2019) Andrew Hii Chii Leong, Yew Vicky, Chia Jia Le
                <br>CAT300 Group Innovation Project, Academic Session 2019/2020, Semester 1</p>
        </div>
        
    </body>
</html>

scp300/templates/main/index.html
{% extends "base.html" %}

{% block content %}
    <ul>purpose
        <li>allow more immersive experience</li>
        <li>propose an recommendatio system for using nueral network</li>
        <li>demonstrate the implementatio of ar technology online shopping platform</li>
    </ul>
    <ol>features
        <li>argumented reality eyewear fitting</li>
        <li>upload and removing of eyewear</li>
        <li>face shape classifier to identify face shape to provide recommendation</li>
        <li>recommnendation system to recommend eyewear</li>
    </ol>
    <ol>tools
        <li>face-api-js</li>
        <li>three.js</li>
        <li>tensorflow</li>
        <li>keras</li>
        <li>flask framework</li>
    </ol>
{% endblock %}

scp300/templates/main/search.html
{% extends "base.html" %}
{% block content %}
<section>
    <div>
        <form id="filterform" name="filter" enctype="multipart/form-data" method="POST" action="">
            <select name='color' id="colorlist">
                <option value="none">none</option>
                {% if colors %}
                {% for color in colors %}
                <option value="{{  color.specColor  }}">{{ color.specColor  }}</option>
                {% endfor %}
                {% endif %}
            </select>
            <select name='shape'id="framelist">
                <option value="none">none</option>
                {% if shapes %}
                {% for shape in shapes %}
                <option value="{{ shape.specShape }}">{{ shape.specShape }}</option>
                {% endfor %}
                {% endif %}
            </select>
            <input id='submit' type='submit' value='search'>
        </form>
    </div>
    <div>
        {% if previous %}
            <p>Color: {{previous['color']}} Shape: {{previous['shape']}} </p>
        {% endif %}

        {% if specs %}
            <p>number of result:{{ specs|length }}</p>
            <div id="resultlist" >
                {% for spec in specs %}
                <!-- <div > -->
                        {% with iurl = url_for ('static',filename=spec.imageURL)  %}
                        {% with surl = spec.shoppingURL %}
                        <div > 
                            <div id="item"><a href="{{ surl }}"><img id="picture" src="{{ iurl }}"></a></div>
                            <p>Color:{{ spec.specColor }}
                            <br>Shape:{{ spec.specShape }}</p>
                        </div>
                           
                        
                    {% endwith %}
                    {% endwith %}
                    <!-- </div> -->
                {% endfor %}
            </div>
        {% endif%}


    </div>
</section>

<style>
        #colorlist {
        background-color: rgb(101, 131, 101);
        color: #fff;
        padding: 6px 12px;
        border-radius: 5px;
        box-shadow: 1px 1px 4px #ccc;
        font-size: 1em;
        font-weight: 520;
        text-align: center;
        width: 110px;
      }

      #framelist {
        background-color: rgb(101, 131, 101);
        color: #fff;
        padding: 6px 12px;
        border-radius: 5px;
        box-shadow: 1px 1px 4px #ccc;
        font-size: 1em;
        font-weight: 520;
        text-align: center;
        width: 110px;
      }

      #submit{
        all:unset;
        margin-left: auto;
        margin-right:auto;
        
        background-color: #000000;
        color: #fff; 
        padding: 4px 12px;
        border-radius: 5px;
        box-shadow: 1px 1px 4px #ccc;
        font-size: 1em;
        font-weight: 600px; 
        width: 100px;
        height: 30px;
        text-align: center; 
        overflow-wrap: break-word;
    }

    #submit:hover{
        background-color:rgb(101, 131, 101);
        font-weight: 650px;
    }

    option:hover{
        background-color: darkseagreen;
    }

    #picture{
        width:50%;
        height:100%;
        margin-left: 25%; 
    }

    #resultlist{
        height:500px;
        overflow: auto;
        display: flex;  
        flex-wrap: wrap;
    }
    #resultlist>div{
     width: 30%;
     height: 45%;
     margin-left: auto;
     margin-right: auto;
     padding: 10px;
     background-color:rgba(255,255,255,0.8) ;
     border-radius: 40px;
     margin: 5px;
    }

    #resultlist>div>p{
     text-align: center;
     width: 30%;
     margin-left: auto;
     margin-right: auto;  
    line-height: 1;  }

    

    #resultlist>div>a{
     width: 30%;
     margin-left: auto;
     margin-right: auto;   
     right:0;
    align-self: center;
    align-content: center;
}

    p{
        line-height: 0.5;
        text-align: center;
    }

    #item{
        margin: auto;
        height: 80%;
        width: 80%;
    }

    ::-webkit-scrollbar {
    width: 8px;
  }
  
  /* Track */
  ::-webkit-scrollbar-track {
    box-shadow: inset 0 0 5px darkseagreen;
    border-radius: 10px;
  }
  
  /* Handle */
  ::-webkit-scrollbar-thumb {
    background: rgb(101, 131, 101);
    border-radius: 10px;
  }
      
</style>
{% endblock %}


scp300/templates/recm/result.html
{% extends "base.html" %}


{% block css %}
    <link rel='stylesheet' type='text/css' href='{{ url_for("static",filename="recm/css/result.css") }}'>
{% endblock%}

{% block content %}
    <div id="h" style="display: flex;">
        <img id='snap' src="{{  url_for('static',filename='recm/save/face.jpg') }}?dummy={{rand}}">
        <div id="result"> 
            <p id="res">Your Faceshape: {{ shape }}</p>
            <p id="below">Below is the similar face shape:</p>
        </div>
       
       
    </div> 
    <hr>
   
    <!-- display all the faces here with there url link -->

    <div id='container'>
        {% if faces %}
        {% for face in faces %}
        <div class="face_container">
            {% with url = url_for('static',filename= face.imageURL) %}
            <div class="item">
                    <img class="face" src='{{ url }}'>
                    <p>#{{ face.specShape }} #{{ face.specColor }}</p>
            </div>
           

            {% endwith %}
        </div>

        {% endfor %}
        {% endif %}

    </div>
  
{% endblock %}

scp300/templates/recm/snapshot.html
{% extends "base.html" %}

{% block content %}
    <p id="system">Recommendation System</p>
    <p id="instruct">Please take a snapshot of your front face</p>
    <form hidden id="form" name="img" enctype="multipart/form-data"></form>


    <div id="buttons">
        <button id='snap'>snap</button>
        <button id='send'>send</button>
    </div>
    <br>
    <div id="snaped">
    <video id="video" autoplay></video>
    <canvas id="canvas"></canvas>
    </div>
    
    <script src="{{ url_for('static',filename='recm/js/video.js') }}"></script>
    <script>
        setupVideo();  
        setupSnapBtn();  
        setupSendBtn();
    </script>
    <style>
        #video{
            margin-left: auto;
            margin-right: auto;
            width: 42%;
            transform: rotateY(180deg);
			-webkit-transform: rotateY(180deg);
           
        }

        #canvas{
            margin-left: auto;
            margin-right: auto;
            width: 42%;
            -webkit-transform: scaleX(-1);
            transform: scaleX(-1);
          
        }

        #snaped{
            display: flex;
            width: 90%;
            margin-left: auto;
            margin-right: auto;
            
        }

        #buttons{
            display: flex;
        }

        #buttons>button{
            all:unset;
            margin-left: auto;
            margin-right:auto;
            
            background-color: #000000;
            color: #fff; 
            padding: 4px 12px;
            border-radius: 10px;
            box-shadow: 1px 1px 4px #ccc;
            font-size: 1.2em;
            font-weight: 600px; 
            width: 100px;
            height: 30px;
            text-align: center; 
            overflow-wrap: break-word;
        }

        #buttons>button:hover{
            background-color:rgb(101, 131, 101);
            font-size: 1.3em;
            font-weight: 650px;
        }

        #system{
            padding-top: 12px;
            font-size: 1.2em;
            font-weight: 600;
            text-align: center;
        }
        #instruct{
            font-size: 1.1em;
            font-weight: 500;
            text-align: center;
        }
        p{
            line-height: 0.5;
        }
    </style>
{% endblock %}